const initialState = {
  songs: [
    {
      id: "song-1",
      title: "Enough",
      author: "NEFFEX",
      fileName: "Enough - NEFFEX.mp3",
      category: "Rock",
      recommended: true,
      songImage: "song1",
    },
    {
      id: "song-2",
      title: "Escapism",
      author: "Yung Logos",
      fileName: "Escapism - Yung Logos.mp3",
      category: "electronic",
      recommended: true,
      songImage: "song2",
    },
    {
      id: "song-3",
      title: "Illusions",
      author: "Anno Domini Beats",
      fileName: "Illusions - Anno Domini Beats.mp3",
      category: "hip-hop",
      recommended: true,
      songImage: "song3",
    },
    {
      id: "song-4",
      title: "In Five Straight Rows",
      author: "Mini Vandals",
      fileName: "In Five Straight Rows - Mini Vandals.mp3",
      category: "electronic",
      recommended: true,
      songImage: "song4",
    },
    {
      id: "song-5",
      title: "Play Dead",
      author: "NEFFEX",
      fileName: "Play Dead - NEFFEX.mp3",
      category: "pop",
      recommended: false,
      songImage: "song5",
    },
    {
      id: "song-6",
      title: "Take Me Back",
      author: "NEFFEX",
      fileName: "Take Me Back - NEFFEX.mp3",
      category: "pop",
      recommended: false,
      songImage: "song6",
    },
    {
      id: "song-7",
      title: "Winning",
      author: "NEFFEX",
      fileName: "Winning - NEFFEX.mp3",
      category: "hip-hop",
      recommended: true,
      songImage: "song7",
    },
    {
      id: "song-8",
      title: "Out On My Skateboard",
      author: "Mini Vandals",
      fileName: "Out On My Skateboard - Mini Vandals.mp3",
      category: "rock",
      recommended: true,
      songImage: "song8",
    },
    {
      id: "song-9",
      title: "Early Oceans",
      author: "Freedom Trail Studio",
      fileName: "Early Oceans - Freedom Trail Studio.mp3",
      category: "alternative",
      recommended: false,
      songImage: "song9",
    },
  ],
  categories: [
    { id: "pop", name: "pop", imageName: "category1" },
    { id: "hip-hop", name: "hip-hop", imageName: "category2" },
    { id: "rock", name: "rock", imageName: "category3" },
    { id: "alternative", name: "alternative", imageName: "category4" },
    { id: "electronic", name: "electronic", imageName: "category5" },
  ],
  videos: [
    { id: 1, videoPath: "https://www.youtube.com/watch?v=Hw278qY6Erw" },
    { id: 2, videoPath: "https://www.youtube.com/watch?v=sNhHMvxpzUw" },
    { id: 3, videoPath: "https://www.youtube.com/watch?v=-MWZU9zn3mU" },
    { id: 4, videoPath: "https://www.youtube.com/watch?v=S5sUwhQ8nTM" },
    { id: 5, videoPath: "https://www.youtube.com/watch?v=T9cjxnuvfuY" },
    { id: 6, videoPath: "https://www.youtube.com/watch?v=LoNSOCRQW0s" },
    { id: 7, videoPath: "https://www.youtube.com/watch?v=DXRY1RFADps" },
    { id: 8, videoPath: "https://www.youtube.com/watch?v=UPhZ6S9Qfnc" },
    { id: 9, videoPath: "https://www.youtube.com/watch?v=JUYS60ZzC4s" },
  ],
};

export default initialState;
