const initialState = {
  songs: [
    {
      id: "song-1",
      title: "Enough",
      author: "NEFFEX",
      fileName: "Enough - NEFFEX.mp3",
      category: "Rock",
      favorite: false,
    },
    {
      id: "song-2",
      title: "Escapism",
      author: "Yung Logos",
      fileName: "Escapism - Yung Logos.mp3",
      category: "electronic",
      favorite: false,
    },
    {
      id: "song-3",
      title: "Illusions",
      author: "Anno Domini Beats",
      fileName: "Illusions - Anno Domini Beats.mp3",
      category: "hip-hop",
      favorite: false,
    },
    {
      id: "song-4",
      title: "In Five Straight Rows",
      author: "Mini Vandals",
      fileName: "In Five Straight Rows - Mini Vandals.mp3",
      category: "electronic",
      favorite: false,
    },
    {
      id: "song-5",
      title: "Play Dead",
      author: "NEFFEX",
      fileName: "Play Dead - NEFFEX.mp3",
      category: "pop",
      favorite: false,
    },
    {
      id: "song-6",
      title: "Take Me Back",
      author: "NEFFEX",
      fileName: "Take Me Back - NEFFEX.mp3",
      category: "pop",
      favorite: false,
    },
    {
      id: "song-7",
      title: "Winning",
      author: "NEFFEX",
      fileName: "Winning - NEFFEX.mp3",
      category: "hip-hop",
      favorite: false,
    },
    {
      id: "song-8",
      title: "Out On My Skateboard",
      author: "Mini Vandals",
      fileName: "Out On My Skateboard - Mini Vandals.mp3",
      category: "rock",
      favorite: false,
    },
    {
      id: "song-9",
      title: "Early Oceans",
      author: "Freedom Trail Studio",
      fileName: "Early Oceans - Freedom Trail Studio.mp3",
      category: "alternative",
      favorite: false,
    },
  ],
  categories: [
    { id: "pop", name: "pop" },
    { id: "hip-hop", name: "hip-hop" },
    { id: "alternative", name: "alternative" },
    { id: "rock", name: "rock" },
    { id: "electronic", name: "electronic" },
  ],
};

export default initialState;
